name: box
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_color_plugin: ^0.0.2
  flutter_easyrefresh: ^2.1.1
  argon_buttons_flutter: 1.0.2
  flutter_spinkit: ^4.1.2
  underline_indicator: ^0.0.2
  shared_preferences: ^0.5.7+3
  dio: ^3.0.9
  flushbar: ^1.10.4
  fluttertoast: ^4.0.0
  flutter_dialogs: ^1.0.4
  flutter_qr_reader: ^1.0.3
  permission_handler: ^3.0.0
  image_picker: ^0.6.7+2
  pin_code_fields: ^3.1.2
  modal_bottom_sheet: ^1.0.0+1
  animated_text_kit: ^2.1.0
  event_bus: ^1.1.0
  qr_flutter: ^3.1.0
  flutter_easyloading: ^1.1.3
  crypto: ^2.1.5
  flutter_aes_ecb_pkcs5: ^0.1.1
  encrypt: ^4.0.2
  smooth_page_indicator: ^0.2.0
  flutter_keyboard_visibility: ^3.2.2
  concentric_transition: ^0.1.1
  skeleton_text: ^1.0.0
  package_info: ^0.4.0+2
  url_launcher: ^5.7.2
  io: ^0.3.3
  bip39: ^1.0.3
  #  cryptography: ^1.4.1
  webview_flutter: ^2.0.1
  rlp: ^1.0.1
  common_utils: ^1.2.1
  jaguar_flutter_asset: ^2.2.0
  date_time_format: ^1.1.0
  google_nav_bar: ^3.1.0
  line_icons: ^0.2.0
  badges: ^1.1.1
  salomon_bottom_bar: ^2.0.0
  flutter_staggered_animations: ^0.1.3
  flutter_svg: ^0.19.3
  lottie: ^0.7.0+1
  keyboard_visibility: ^0.5.6
  photo_view: ^0.10.3
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
#    - family: ZCOOLXiaoWei
#      fonts:
#        - asset: assets/fonts/ZCOOLXiaoWei-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/js/
    - assets/html/
    - images/
    - images/login_logo.png
    - images/nav_home.png
    - images/nav_home_active.png
    - images/nav_wallet.png
    - images/nav_wallet_active.png
    - images/nav_profile.png
    - images/nav_profile_active.png
    - images/profile_lines.png
    - images/profile_network.png
    - images/profile_connect.png
    - images/profile_wallet.png
    - images/profile_backups.png
    - images/profile_banner.png
    - images/profile_display_currency.png
    - images/profile_account_permissions.png
    - images/profile_lanuge.png
    - images/profile_info.png
    - images/profile_reset_password.png
    - images/wallet_card.png
    - images/wallet_card_blue.png
    - images/check_box_normal.png
    - images/check_box_select.png
    - images/main_know_icon_1.png
    - images/main_know_icon_2.png
    - images/main_know_icon_3.png
    - images/home_bg.png
    - images/home_send.png
    - images/home_aens.png
    - images/home_game.png
    - images/home_receive.png
    - images/home_settings.png
    - images/home_logo.png
    - images/home_search.png
    - images/home_send_token.png
    - images/home_receive_token.png
    - images/home_names.png
    - images/home_record.png
    - images/home_logo_left.png
    - images/home_financial.png
    - images/splasn_logo.png
    - images/defi_bg.png
    - images/apple-touch-icon.png
    - images/logo.png
    - images/defi_list.png
    - images/defi_info.png
    - images/splasn_logo.png
    - images/ranking_text.png
    - images/ranking_logo.png
    - images/ranking_one.png
    - images/splasn_logo.png
    - images/defi_bg.png
    - images/defi_logo.png
    - images/card_top.png
    - images/card_bottom.png
    - images/setting_lanuage.png
    - images/setting_node.png
    - images/setting_save.png
    - images/setting_version.png
    - images/tab_swap.png
    - images/tab_swap_p.png
    - images/tab_home.png
    - images/tab_home_p.png
    - images/tab_app.png
    - images/swap_my.png
    - images/swap_send.png
    - images/apps_wetrue.png
    - images/aepp_forum.png
    - images/aepp_superhero.png
    - images/no_data.png
    - images/no_net.png
    - images/base_logo.png
    - images/index_bg1.png
    - images/index_bg2.png
    - images/index_bg4.png
    - images/together.png
    - images/tether.png
    - images/token_add.png
    - home_swap.png
    - home_token.png
    - no_record.png
    - name_point.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en  # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
